export const words = [
  "Fitness",
  "Health",
  "Workout",
  "Movement",
  "Healthy Lifestyle",
];

export const heroImages = [
  "/intro.jpg",
  "/intro1.png",
  "/intro2.jpg",
  "/intro3.jpg",
  "/intro4.webp",
];

export const programs = [
  {
    title: "Strength Training",
    desc: "Quản lý giáo án, huấn luyện viên cá nhân và tiến độ tập luyện cho từng hội viên.",
    active: false,
    icon: "🏋️",
  },
  {
    title: "Yoga Class",
    desc: "Sắp xếp lớp học, số lượng học viên và lịch đặt chỗ theo thời gian thực.",
    active: false,
    icon: "🧘",
  },
  {
    title: "Bodybuilding",
    desc: "Theo dõi gói tập, check-in, thanh toán và hiệu suất vận hành phòng gym tập trung.",
    active: true,
    icon: "💪",
  },
  {
    title: "Weight Loss",
    desc: "Quản lý mục tiêu thể chất, đo chỉ số cơ thể và lộ trình chăm sóc khách hàng.",
    active: false,
    icon: "🔥",
  },
];

export const pricing = [
  {
    name: "Discover",
    monthlyPrice: "300000",
    annualPrice: "3000000",
    features: ["5 lớp mỗi tuần", "4 buổi PT mỗi tháng", "Báo cáo cơ bản"],
    highlight: false,
  },
  {
    name: "Enterprise",
    monthlyPrice: "500000",
    annualPrice: "5000000",
    features: [
      "PT không giới hạn",
      "Báo cáo nâng cao",
      "Quản lý check-in thông minh",
    ],
    highlight: true,
  },
  {
    name: "Professional",
    monthlyPrice: "900000",
    annualPrice: "9000000",
    features: ["8 lớp mỗi tháng", "Quản lý HLV", "Theo dõi doanh thu"],
    highlight: false,
  },
];

export const trainers = [
  {
    name: "Bùi Hữu Nam",
    role: "Senior Bodybuilding Coach",
    img: "../../../public/me.jpg",
    bio: "Bùi Hữu Nam là một huấn luyện viên dày dặn kinh nghiệm với hơn 10 năm thay đổi vóc dáng cho học viên.",
    rate: "500k/hr",
    status: "HN Fitcore",
    badge: "available",
    skills: ["Gym", "Nutrition", "Bulking", "+2"],
    email: "nam.bui@hnfitcore.com",
    phone: "0367 397 104",
    address: "Cơ sở 1 - Cầu Giấy, Hà Nội",
    certifications: [
      "NASM Certified Personal Trainer",
      "Chứng nhận chuyên gia Dinh dưỡng Thể thao (ISSA)",
    ],
    teaching: [
      "Bodybuilding Advanced",
      "Strength Training",
      "Kiểm soát cân nặng",
    ],
  },
  {
    name: "Alex Johnson",
    role: "Yoga Master",
    img: "../../../public/Stones.jpg",
    bio: "Alex là một chuyên gia Yoga giúp bạn tìm lại sự cân bằng giữa tâm trí và cơ thể một cách hiệu quả.",
    rate: "300k/hr",
    status: "Freelancer",
    badge: "",
    skills: ["Yoga", "Meditation", "Flexibility", "+1"],
    email: "alex.j@gmail.com",
    phone: "0988 123 456",
    address: "Cơ sở 2 - Quận 1, TP.HCM",
    certifications: [
      "200-Hour RYT Yoga Alliance",
      "Chứng chỉ Trị liệu Thiền định",
    ],
    teaching: ["Hatha Yoga", "Vinyasa Flow", "Meditation Core"],
  },
  {
    name: "Minh Tuấn",
    role: "Strength & Conditioning",
    img: "../../../public/garcia.webp",
    bio: "Chuyên gia đào tạo vận động viên chuyên nghiệp với các giáo án sức mạnh nâng cao.",
    rate: "450k/hr",
    status: "HN Fitcore",
    badge: "hot",
    skills: ["Powerlifting", "Crossfit", "Cardio", "+3"],
    email: "tuan.minh@hnfitcore.com",
    phone: "0912 345 678",
    address: "Cơ sở 1 - Cầu Giấy, Hà Nội",
    certifications: [
      "CSCS (Certified Strength and Conditioning Specialist)",
      "Cử nhân Giáo dục Thể chất",
    ],
    teaching: ["Powerlifting", "Crossfit", "Huấn luyện Thể lực chuyên sâu"],
  },
  {
    name: "Sarah Kim",
    role: "Weight Loss Specialist",
    img: "../../../public/Sarah Kim.png",
    bio: "Đồng hành cùng bạn trên hành trình giảm mỡ, siết cơ khoa học mà không cần nhịn ăn cực đoan.",
    rate: "350k/hr",
    status: "Freelancer",
    badge: "available",
    skills: ["Diet", "HIIT", "Pilates", "+1"],
    email: "sarah.kim@gmail.com",
    phone: "0933 555 777",
    address: "Cơ sở 3 - Đống Đa, Hà Nội",
    certifications: [
      "ACE Weight Management Specialist",
      "Chứng chỉ HLV Pilates Quốc tế",
    ],
    teaching: ["Weight Loss Bootcamp", "Pilates", "HIIT Cardio"],
  },
  {
    name: "Linda",
    role: "Kickboxing Coach",
    img: "../../../public/Linda.png",
    bio: "Huấn luyện viên võ thuật tự do giúp bạn rèn luyện phản xạ, đốt mỡ và tự vệ thực chiến.",
    rate: "400k/hr",
    status: "HN Fitcore",
    badge: "",
    skills: ["Boxing", "Muay Thai", "Fitness", "+2"],
    email: "linda.fight@hnfitcore.com",
    phone: "0977 888 999",
    address: "Cơ sở 1 - Cầu Giấy, Hà Nội",
    certifications: [
      "Đai đen Taekwondo",
      "Huấn luyện viên Muay Thai chuyên nghiệp",
    ],
    teaching: ["Kickboxing", "Muay Thai Cơ Bản", "Phản xạ tự vệ"],
  },
  {
    name: "Ngọc Diệp",
    role: "Interactive Designer",
    img: "../../../public/anna.jpg",
    bio: "Chuyên gia thiết kế lộ trình tập luyện cá nhân hóa theo từng thể trạng đặc biệt của khách hàng.",
    rate: "300k/hr",
    status: "Freelancer",
    badge: "free trial",
    skills: ["Planning", "Anatomy", "Recovery", "+4"],
    email: "diep.ngoc@gmail.com",
    phone: "0909 111 222",
    address: "Cơ sở 2 - Quận 1, TP.HCM",
    certifications: [
      "Chứng chỉ Phục hồi chức năng",
      "Chuyên gia Phân tích Vận động",
    ],
    teaching: [
      "Thiết kế Lộ trình Dinh dưỡng",
      "Bài tập Phục hồi (Recovery)",
      "Posture Correction",
    ],
  },
];